version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install yfinance pandas matplotlib

  build:
    commands:
      - echo Running stock analysis script...
      - python stock_analysis.py

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: yes
